### RHCP 티켓 등록
POST http://localhost/events/RHCP
Content-Type: application/json

{
  "tickets": 10
}

### DjMadlib 티켓 등록
POST http://localhost/events/DjMadlib
Content-Type: application/json

{
  "tickets": 10
}

### 모든 티켓 보기
GET http://localhost/events

### RHCP 티켓 보기
GET http://localhost/events/RHCP

### RHCP 티켓 구매
POST http://localhost/events/RHCP/tickets
Content-Type: application/json

{
  "tickets": 1
}

### RHCP 티켓 판매 중단
DELETE http://localhost/events/RHCP